from ttkfun import *
import ttkfun
from tkinter import ttk

def ext():
    win.destroy()
def rhybeam():
    def ext4():
        win4.destroy()
    def rslt3():
        try:
           yB = int(yb.get())
           xB = int(xb.get())
           yA= int(ya.get())
           xA = int(xa.get())
           c = (-xA*xB) - (yA*yB)
           a = (-xA)/(yA)
           b = (-c)/(yA)
           A = str(a)
           B = str(b)
           msg = "the equation" + "\n" + "y = " + A + "x +" + B
           msgbox('showinfo', 'result', msg)
           if ttkfun.i == 'ok':
               win4.destroy()
        except:
           msgbox('showerror', 'error', 'enter a real number please')
    win4 = Toplevel()
    win4.title('steering beam')
    win4.config(background='lightblue')
    ttk.Label(win4, text='put ihdathyat the point').pack(pady=20, padx=20)
    frm1 = Frame(win4)
    frm1.pack()
    ttk.Label(frm1, text='   x   ').grid(row=1, column=0)
    xb = StringVar()
    en1 = ttk.Entry(frm1, textvariable=xb)
    en1.focus()
    en1.grid(row=1, column=1)
    ttk.Label(frm1, text='   y   ').grid(row=1, column=2)
    yb = StringVar()
    en2 = ttk.Entry(frm1, textvariable=yb)
    en2.grid(row=1, column=3)

    ttk.Label(win4, text='put ihdathyat chouaa nadimi').pack(pady=20, padx=20)
    frm2 = Frame(win4)
    frm2.pack()
    ttk.Label(frm2, text='   x   ').grid(row=1, column=0)
    xa = StringVar()
    en1 = ttk.Entry(frm2, textvariable=xa)
    en1.grid(row=1, column=1)
    ttk.Label(frm2, text='   y   ').grid(row=1, column=2)
    ya = StringVar()
    en2 = ttk.Entry(frm2, textvariable=ya)
    en2.grid(row=1, column=3)
    confttk(win4, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm1, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm2, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    ttk.Button(win4, text='result', command=rslt3).pack(pady=20, padx=20)
    ttk.Button(win4, text='back', command=ext4).pack(pady=20, padx=20)
    win4.grab_set()
def strbeam():
    def ext3():
        win3.destroy()
    def rslt2():
        try:
           yB = int(yb.get())
           xB = int(xb.get())
           yA= int(ya.get())
           xA = int(xa.get())
           c = xA*yB - (yA*xB)
           a = (-yA)/(-xA)
           b = (-c)/(-xA)
           A = str(a)
           B = str(b)
           msg = 'the equation'+"\n" + 'y = '+A+'x +'+B
           msgbox('showinfo', 'result', msg)
           if ttkfun.i == 'ok':
               win3.destroy()
        except:
           msgbox('showerror','error','enter a real number please')
    win3 = Toplevel()
    win3.title('steering beam')
    win3.config(background='lightblue')
    ttk.Label(win3, text='put ihdathyat the point').pack(pady=20, padx=20)
    frm1 = Frame(win3)
    frm1.pack()
    ttk.Label(frm1, text='   x   ').grid(row=1, column=0)
    xb = StringVar()
    en1 = ttk.Entry(frm1, textvariable=xb)
    en1.focus()
    en1.grid(row=1, column=1)
    ttk.Label(frm1, text='   y   ').grid(row=1, column=2)
    yb = StringVar()
    en2 = ttk.Entry(frm1, textvariable=yb)
    en2.grid(row=1, column=3)

    ttk.Label(win3, text='put ihdathyat chouaa twjih').pack(pady=20, padx=20)
    frm2 = Frame(win3)
    frm2.pack()
    ttk.Label(frm2, text='   x   ').grid(row=1, column=0)
    xa = StringVar()
    en1 = ttk.Entry(frm2, textvariable=xa)
    en1.grid(row=1, column=1)
    ttk.Label(frm2, text='   y   ').grid(row=1, column=2)
    ya = StringVar()
    en2 = ttk.Entry(frm2, textvariable=ya)
    en2.grid(row=1, column=3)
    confttk(win3, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm1, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm2, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    ttk.Button(win3, text='result', command=rslt2).pack(pady=20, padx=20)
    ttk.Button(win3, text='back', command=ext3).pack(pady=20, padx=20)
    win3.grab_set()
def topn():
    def ext2():
        win2.destroy()
    def reslt():
        try:
           yB = int(yb.get())
           xB = int(xb.get())
           yA= int(ya.get())
           xA = int(xa.get())
           a = (yA - yB) / (xA - xB)
           b = yB - a * xB
           A = str(a)
           B = str(b)
           msg =  'the equation' + "\n"+ 'y = '+A+'x +'+B
           msgbox('showinfo', 'result', msg)
           if ttkfun.i == 'ok':
               win2.destroy()
        except:
           msgbox('showerror','error','enter a real number please')
    win2 = Toplevel()
    win2.title('tow points')
    win2.config(background='lightblue')
    ttk.Label(win2, text='put ihdathyat the first point').pack(pady=20, padx=20)
    frm1 = Frame(win2)
    frm1.pack()
    ttk.Label(frm1, text='   x   ').grid(row=1, column=0)
    xb = StringVar()
    en1 = ttk.Entry(frm1, textvariable=xb)
    en1.focus()
    en1.grid(row=1, column=1)
    ttk.Label(frm1, text='   y   ').grid(row=1, column=2)
    yb = StringVar()
    en2 = ttk.Entry(frm1, textvariable=yb)
    en2.grid(row=1, column=3)

    ttk.Label(win2, text='put ihdathyat the second number').pack(pady=20, padx=20)
    frm2 = Frame(win2)
    frm2.pack()
    ttk.Label(frm2, text='   x   ').grid(row=1, column=0)
    xa = StringVar()
    en1 = ttk.Entry(frm2, textvariable=xa)
    en1.grid(row=1, column=1)
    ttk.Label(frm2, text='   y   ').grid(row=1, column=2)
    ya = StringVar()
    en2 = ttk.Entry(frm2, textvariable=ya)
    en2.grid(row=1, column=3)
    confttk(win2, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm1, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    confttk(frm2, bgl='lightblue', bge='lightblue', fnt='arial 15 bold')
    ttk.Button(win2, text='result', command=reslt).pack(pady=20, padx=20)
    ttk.Button(win2, text='back', command=ext2).pack(pady=20, padx=20)

    win2.grab_set()
win = Tk()
win.title('maths')
win.config(background='pink')
ttk.Label(win, text='').pack()
confttk(win, fgl='blue', fnt='tahoma 15 bold underline', bgl='pink')
frm = Frame(win, background='pink')
frm.pack(pady=5, padx=5)
ttk.Label(frm, text='defined by').grid(row=0, column=1, pady=10, padx=10)
ttk.Button(frm, text='tow pints', command=topn).grid(row=0, column=0, pady=10, padx=10)
ttk.Label(frm, text='defined by').grid(row=1, column=1, pady=10, padx=10)
ttk.Button(frm, text='point and couaa twjih', command=strbeam).grid(row=1, column=0, pady=10, padx=10)
ttk.Label(frm, text='defined by').grid(row=2, column=1, pady=10, padx=10)
ttk.Button(frm, text='point and choaa nadimi', command=rhybeam).grid(row=2, column=0, pady=10, padx=10)
confttk(frm, bgl='pink', fnt='arial 15 underline')
ttk.Button(win, text='exit', command=ext).pack(pady=20, padx=20)
win.mainloop()